remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme
basepath: arduino_eurorack
title: Arduino Eurorack
description: [A library for creating Eurorack modules using Arduino devices]